---
- name: Create temporary directory
  tempfile:
    state: directory
  register: _tmpdir
- set_fact:
    tmpdir: "{{ _tmpdir.path }}"

- name: Create temporary kubeconfig file
  set_fact:
    kubeconfig: "{{ tmpdir }}/kube"

- name: Login to OpenShift
  command: >
    oc login "{{ ocp_server }}"
    --username "{{ ocp_username }}"
    --password "{{ ocp_password }}"
    --config {{ kubeconfig }}
    --insecure-skip-tls-verify

- name: Get OpenShift token
  command: oc whoami -t --config "{{ kubeconfig }}"
  register: _ocptoken
- set_fact:
    ocp_token: "{{ _ocptoken.stdout }}"
