---
# - block:
- name: Get the Jenkins secret name
  shell: "oc get sa/jenkins -o jsonpath={.secrets[0].name} -n cicd"  
  register: jenkins_secret_stdout

- name: Set Jenkins Secret Name Fact
  set_fact: 
    jenkins_secret_name: "{{ jenkins_secret_stdout.stdout }}"

- debug:
    var: jenkins_secret_name

- name: Get the Jenkins secret content
  shell: "oc get secret {{ jenkins_secret_name }} -o=jsonpath={.data.token} -n cicd | base64 -d "  
  register: jenkins_token_stdout

- name: Set Jenkins Secret Content Fact
  set_fact: 
    jenkins_token: "{{ jenkins_token_stdout.stdout }}"

- debug:
    var: jenkins_token

- name: Get Jenkins Route Address
  shell: "oc get route/jenkins -o jsonpath={.spec.host} -n cicd"
  register: jenkins_route_stdout

- name: Get Jenkins Job Route Fact
  set_fact:
    jenkins_build_job_uri: "https://{{ jenkins_route_stdout.stdout }}/job/cicd/job/cicd-e2e-pipeline-sample/build"

- name: Invoke Jenkins Pipeline Job
  uri:
    url: "{{ jenkins_build_job_uri }}"
    method: POST
    validate_certs: no
    status_code:
    - 302
    headers:
      Authorization: "Bearer {{ jenkins_token }}"